version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: metal
      MYSQL_DATABASE: test_interview
    ports:
      - "3306:3306"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-container
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-container
    ports:
      - "2181:2181"

  membership:
    build:
      context: ./membership
    ports:
      - "8081:8080"
    depends_on:
      - mysql

  payment-dummy:
    build:
      context: ./payment-dummy
    ports:
      - "8082:8080"
    depends_on:
      - mysql

  satu:
    build:
      context: ./satu
    ports:
      - "8083:8080"
    depends_on:
      - mysql
      - kafka

  dua:
    build:
      context: ./dua
    ports:
      - "8084:8080"
    depends_on:
      - mysql
      - kafka

  tiga:
    build:
      context: ./tiga
    ports:
      - "8085:8080"
    depends_on:
      - mysql

  empat:
    build:
      context: ./empat
    ports:
      - "8086:8080"
    depends_on:
      - mysql

  lima:
    build:
      context: ./lima
    ports:
      - "8087:8080"
    depends_on:
      - mysql